### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'outcome'

### ISSUE THREAD

**Issue by ggravlingen** [pytest-dev/pytest-nunit#54]
Hi,

I'm getting the error below on version 1.0.0. I'm pretty sure there is a failed test that causes this; one in which I'm patching the result of a function.

When running the test suit without xdist, there are no errors.

```
platform linux -- Python 3.8.12, pytest-7.1.1, pluggy-1.0.0
django: settings: config.settings.test (from option)
rootdir: /workspaces/system, configfile: pyproject.toml
plugins: forked-1.4.0, django-4.5.2, Faker-13.3.4, azurepipelines-1.0.3, flaky-3.7.0, anyio-3.5.0, xdist-2.5.0, cov-3.0.0, nunit-1.0.0
gw0 [1282] / gw1 [1282] / gw2 [1282] / gw3 [1282]
................................................................................................................................................................ [ 12%]
................................................................................................................................................................ [ 24%]
................................................................................................................................................................ [ 37%]
...........................Running test suite
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/xdist/dsession.py", line 117, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/xdist/dsession.py", line 140, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/xdist/dsession.py", line 275, in worker_testreport
INTERNALERROR>     self.config.hook.pytest_runtest_logreport(report=rep)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pytest_nunit/plugin.py", line 312, in pytest_runtest_logreport
INTERNALERROR>     reporter.record_testreport(report)
INTERNALERROR>   File "/usr/src/.venv/lib/python3.8/site-packages/pytest_nunit/plugin.py", line 181, in record_testreport
INTERNALERROR>     elif "failed" in [r["call-report"].outcome, testreport.outcome]:
```

I've search the issues here and there seem to be no one else having reported this, which makes me believe this is a local issue. Any pointers where to look would be appreciated though.

**Comment by ggravlingen** [comment]
I tried adding `--cov-report=xml` to the `pytest` command and delete all XML-files and the folder containing the HTML-reports. This made the tests go through. Still not sure why this is happening though?

**Comment by tonybaloney** [comment]
Looks like the issue is here:
https://github.com/pytest-dev/pytest-nunit/blob/master/pytest_nunit/plugin.py#L180 where `r["call-report"]` is assigned as `None` in the setup phase, but it could hit this conditional _if_ setup failed and it would try and read `.outcome` on None.

Needs
 - Reproducible test
 - Better assertions
